theme: jekyll-theme-minimal
title: waves 
author: H2O
email: mizuki.job@gmail.com

# social links
[mizukirc@github](https://github.com/mizukirc)

show_excerpts: True # set to false to remove excerpts on the homepage
