theme: jekyll-theme-minimal
title: github pages 
author: H2O
email: ...

# social links
github_account: https://github.com/mizukirc

show_excerpts: True # set to false to remove excerpts on the homepage
