theme: jekyll-theme-architect
title: github pages 
author: H2O
email: mizuki.job@gmail.com

# social links
github_account: https://github.com/mizukirc)

show_excerpts: False # set to false to remove excerpts on the homepage
