theme: jekyll-theme-minimal
title: github_pages 
author: H2O
email: mizuki.job@gmail.com

# social links
github_account: https://github.com/mizukirc)

show_excerpts: True # set to false to remove excerpts on the homepage
