theme: jekyll-theme-minimal
title: github pages 
author: mizukirc
email: ...

# social links
github_account: https://github.com/mizukirc

show_excerpts: False # set to false to remove excerpts on the homepage
