theme: minima
author: mizukirc
email: mizuki.job@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write 

# social links
github_username: mizukirc

show_excerpts: true # set to false to remove excerpts on the homepage
